// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_CONTROLLER_CONTROLLER_H_
#define FLATBUFFERS_GENERATED_CONTROLLER_CONTROLLER_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

namespace Controller {

struct PlayerState;
struct PlayerStateBuilder;

struct PlayerState FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef PlayerStateBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_X = 4,
    VT_Y = 6
  };
  int32_t x() const {
    return GetField<int32_t>(VT_X, 0);
  }
  int32_t y() const {
    return GetField<int32_t>(VT_Y, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_X, 4) &&
           VerifyField<int32_t>(verifier, VT_Y, 4) &&
           verifier.EndTable();
  }
};

struct PlayerStateBuilder {
  typedef PlayerState Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_x(int32_t x) {
    fbb_.AddElement<int32_t>(PlayerState::VT_X, x, 0);
  }
  void add_y(int32_t y) {
    fbb_.AddElement<int32_t>(PlayerState::VT_Y, y, 0);
  }
  explicit PlayerStateBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<PlayerState> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<PlayerState>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<PlayerState> CreatePlayerState(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t x = 0,
    int32_t y = 0) {
  PlayerStateBuilder builder_(_fbb);
  builder_.add_y(y);
  builder_.add_x(x);
  return builder_.Finish();
}

inline const Controller::PlayerState *GetPlayerState(const void *buf) {
  return ::flatbuffers::GetRoot<Controller::PlayerState>(buf);
}

inline const Controller::PlayerState *GetSizePrefixedPlayerState(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<Controller::PlayerState>(buf);
}

inline bool VerifyPlayerStateBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<Controller::PlayerState>(nullptr);
}

inline bool VerifySizePrefixedPlayerStateBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<Controller::PlayerState>(nullptr);
}

inline void FinishPlayerStateBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<Controller::PlayerState> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedPlayerStateBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<Controller::PlayerState> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace Controller

#endif  // FLATBUFFERS_GENERATED_CONTROLLER_CONTROLLER_H_
